# Generated by Django 5.2.6 on 2025-10-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_creat_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
