# Generated by Django 5.2.6 on 2025-10-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_creat_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='creat_at',
            new_name='create_at',
        ),
    ]
