# Generated by Django 5.2.6 on 2025-10-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_creat_at_student_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.TextField(),
        ),
    ]
