# Generated by Django 5.2.7 on 2025-11-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.CharField(),
        ),
    ]
