# Generated by Django 5.2.6 on 2025-10-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='creat_at',
        ),
    ]
