# Generated by Django 5.2.6 on 2025-10-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_blog_creat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
